{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "Parameters": {
    "Workspace": {
      "type": "string"
    }
  },
  "resources": [
    {
      "id": "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/1fa1528e-f746-4794-8a41-14827f4cb798')]",
      "name": "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/1fa1528e-f746-4794-8a41-14827f4cb798')]",
      "type": "Microsoft.OperationalInsights/workspaces/providers/alertRules",
      "kind": "Scheduled",
      "apiVersion": "2021-03-01-preview",
      "properties": {
        "queryPeriod": "1h",
        "queryFrequency": "1h",
        "description": "'This query identifies evidence of failed login attempts from a large number of distinct users on a Pulse Connect Secure VPN server'\n",
        "triggerThreshold": 0,
        "query": "let threshold = 100;\nPulseConnectSecure\n| where Messages startswith \"Login failed\"\n| summarize dcount(User) by Computer, bin(TimeGenerated, 15m)\n| where dcount_User > threshold\n",
        "name": "PulseConnectSecure - Large Number of Distinct Failed User Logins",
        "triggerOperator": "gt",
        "severity": "Medium",
        "tactics": [
          "CredentialAccess"
        ],
        "entityMappings": [
          {
            "entityType": "Host",
            "fieldMappings": [
              {
                "columnName": "Computer",
                "identifier": "FullName"
              }
            ]
          }
        ],
        "status": "Available"
      }
    }
  ]
}
